### ISSUE TITLE
Windows cygwin support

### ISSUE THREAD

**Issue by puneetsl** [aeroxis/sultan#10]
There should be a way to specify Cygwin base directory while loading Sultan. 
This would able to use Sultan in Windows as well.

Thanks,
Puneet

**Comment by davydany** [comment]
@puneetsl Have you tried using Sultan's Context Management feature? 

http://sultan.readthedocs.io/en/latest/sultan-examples.html#example-2-sultan-with-context-management

**Comment by davydany** [comment]
Closing since I believe this feature addresses your issue. Feel free to open this issue up if you feel otherwise @puneetsl
