### ISSUE TITLE
Pydoc

### ISSUE THREAD

**Issue by j3r1ch0** [aeroxis/sultan#11]
I think the "pydoc" should be filled out with classes and methods in order to provide better documentation for the project. I tried "pydoc sultan" on my local machine but the lack of information there forced me to search out this github page to figure out exactly how to use it in my scripts.

**Comment by j3r1ch0** [comment]
I think the "pydoc" should be filled out with classes and methods in order to provide better documentation for the project. I tried "pydoc sultan" on my local machine but the lack of information there forced me to search out this github page to figure out exacltly how to use it in my scripts.

**Comment by davydany** [comment]
that's a good idea. I'll do that!

**Comment by j3r1ch0** [comment]
Awesome! Thanks!

**Comment by davydany** [comment]
@j3r1ch0 I added documentation to the classes that are publicly usable, and added a read the docs: http://sultan.readthedocs.io/en/latest/

**Comment by davydany** [comment]
@j3r1ch0 Let me know if that's what you're looking for, and i'll close this ticket.

**Comment by j3r1ch0** [comment]
@davydany The way you did it works fine. Thanks for getting around to it quickly! Have a good one.

**Comment by davydany** [comment]
@j3r1ch0 Great! Thanks! Please share Sultan with other devs you know :smile:
