### ISSUE TITLE
Possible merger  with Fabric?

### ISSUE THREAD

**Issue by rajaravivarma-r** [aeroxis/sultan#34]
Hi author of Sultan, I just noticed your project from Hacker News. Sorry if this sounds stupid. It is subjective, I know but I am going to give my opinions anyway.

There is this awesome project called 'Fabric' for automating tasks using command line utilities through Python, and much more. We have already used that in place of Ansible and it served pretty well for us. I believe both of the projects (Sultan & Fabric) serves the same purpose, while Fabric doing much more (not being offensive).

Right now Fabric has reached a tipping point as mentioned in the [Roadmap](http://www.fabfile.org/roadmap.html). So why not contribute the best parts of your project to Fabric so that it benefits Fabric's code base.

For your reference, 
1) [Invoke](https://github.com/pyinvoke/invoke) 
2) [Fabric](https://github.com/fabric/fabric/)

Please close this if this is completely ridiculous.

**Comment by davydany** [comment]
It's a good idea that you're recommending. I don't think Sultan's goals are to necessarily be in the same landscape as Fabric, or Invoke. Fabric is a deployment tool, and Invoke is a task tool. I think Sultan is more of a general all purpose tool where you can use it as part of any application. 

For example, if you have a task to get some remote files, package it up and send it over to another environment, you can use Sultan to do this, and be on your way. It is not necessarily a deployment task or a build task. This example would certainly fall under some sort of DevOps work, but there are other use cases for what Sultan can be used.

I will certainly reach out to folks at Invoke and Fabric to see if they're interested in including Sultan as part of their projects.

**Comment by rajaravivarma-r** [comment]
Thank you for replying with clear use cases. I definitely see where Sultan can be used as a minimal library than full blown deployment solutions like Fabric.
