### ISSUE TITLE
question: support <port> option for remote host

### ISSUE THREAD

**Issue by jeremyschulman** [aeroxis/sultan#36]
Hi Sultan team,

Thank you for developing and sharing this package.  Is it possible to provide an SSH port number, alternative to 22 via the API?  I know I could workaround this using an .ssh/config setting.  I'd prefer to have this ability supported natively in the API if possible.

Cheers,
-- Jeremy

**Comment by davydany** [comment]
Good idea. I'll add it as part of the next release

**Comment by davydany** [comment]
This is fixed now in Sultan v0.6. http://sultan.readthedocs.io/en/latest/sultan-ssh-examples.html#example-3-passing-additional-options-port

I'm going to close this ticket, but please reopen it if it is still an issue.
