### ISSUE TITLE
Getting output on SSH connection

### ISSUE THREAD

**Issue by ssbanerje** [aeroxis/sultan#41]
Is there any way to get `STDOUT` or `STDERR` streams as strings or lists from the sultan API? I am particularly interested in the remote SSH based commands.

**Comment by davydany** [comment]
I've implemented this in Version 0.6. Here is the documentation for it: http://sultan.readthedocs.io/en/latest/sultan-examples.html#example-12-results-from-a-command

I'm closing this ticket, but please reopen it if it is still an issue. Thank you!
