### ISSUE TITLE
Hyphenated commands: Using apt-get like yum was used in the examples

### ISSUE THREAD

**Issue by dcbb** [aeroxis/sultan#42]
In the examples, the following very elegant syntax is used to install something with yum:
  
    with Sultan.load(sudo=True, hostname="myserver.com") as sultan:
      sultan.yum("install -y tree").run()

I'd love to use this with `apt-get`, but the hyphen collides with Python syntax, obviously. Is there a way to achieve that?

Of course I could do `sultan.sudo("apt-get install ...").run()`, but I really like the idea of having the `sudo` in the contest.

Tried `apt_get`, which fails as `_` is not replaced, probably for good reason.

**Comment by davydany** [comment]
Doh! That's a great catch! I'll fix this bug as part of the next release!

**Comment by davydany** [comment]
I fixed this in `Sultan v0.6`. Here is how to use it: http://sultan.readthedocs.io/en/latest/sultan-examples.html#example-10-commands-with-hyphones-i-e-apt-get

I'm closing the ticket, but please reopen it if it is still an issue.
