### ISSUE TITLE
Use custom user for SSH connection

### ISSUE THREAD

**Issue by Jenselme** [aeroxis/sultan#46]
Hi,

I think it would be useful to be able to select which user to use when running an SSH connection. The syntax could be something like: `with Sultan.load(hostname='aot@mydomain.com') as sultan`.

It currently tries to connect me as `jenselme@aot@mydomain.com` which is invalid.

**Comment by davydany** [comment]
Try this:

```
with Sultan.load(user='aot', hostname='mydomain.com') as sultan:
    sultan.ls('/').run()

```

**Comment by davydany** [comment]
Let me know if that works for you, and close the ticket if it works for you.

**Comment by Jenselme** [comment]
It works, thanks.
