### ISSUE TITLE
Unreachable code in api.py

### ISSUE THREAD

**Issue by BartoszCki** [aeroxis/sultan#60]
Hi, I was reading Sultan's code and PyCharm highlighted a piece of code that makes some code unreachable.

It seems like David Daniel's commit of 30th November made lines 222 to 288 impossible to execute as they follow a return statement (line 219).

**Comment by davydany** [comment]
@BartoszCki is it this? https://github.com/aeroxis/sultan/commit/e08b38ba5aeb67923345f7fa10afe48377694ce6

If not, can you paste a link to the code that is unreachable? Thanks!

**Comment by BartoszCki** [comment]
@davydany Yes, there is a return statement in line 219 so the code that follows it will never be executed.

I'm not sure if I understand the change correctly but I think that maybe the 'return result' should't be there.

**Comment by davydany** [comment]
DOH!!! You're right! I'll fix it asap and issue a new release!

Thanks for finding it!

**Comment by davydany** [comment]
This is resolved. Please use `Sultan==0.7.1`
